name: update-flake-lock-ex-simple
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '0 0 * * 0' # runs weekly on Sunday at 00:00

jobs:
  example-lock:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Github App Token
        uses: navikt/github-app-token-generator@v1
        id: github-app-token
        with:
          app-id: ${{ vars.NIXOS_ASIA_APP_ID }}
          private-key: ${{ secrets.NIXOS_ASIA_PRIVATE_KEY }}
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
      - name: Update flake.lock
        uses: DeterminateSystems/update-flake-lock@main
        id: update-flake-lock
        with:
          commit-msg: "chore(example): Update simple/flake.lock"
          pr-title: "Update example/simple/flake.lock"
          pr-body: |
            Automated changes by the [update-flake-lock](https://github.com/DeterminateSystems/update-flake-lock) GitHub Action.

            ```
            {{ env.GIT_COMMIT_MESSAGE }}
            ```
          pr-labels: |
            automated
          path-to-flake-dir: 'example/simple'
          branch: "update_flake_lock_ex_simple"
          token: ${{ steps.github-app-token.outputs.token }}
      - run: "gh pr merge --auto --rebase --delete-branch ${{ steps.update-flake-lock.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ github.token }}
